EXEC dbo.deploy_seed_calendar
EXEC dbo.deploy_seed_conference
EXEC dbo.deploy_seed_contact
EXEC dbo.deploy_seed_field
EXEC dbo.deploy_seed_home_field
EXEC dbo.deploy_seed_league
EXEC dbo.deploy_seed_permit 
EXEC dbo.deploy_seed_team
EXEC dbp.deploy_seed_team_day_off